---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: giteas.gpte.opentlc.com
spec:
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Gitea is the Schema for the giteas API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            description: Status defines the observed state of Gitea
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            description: Spec defines the desired state of Gitea
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:

              postgresqlSetup:
                description: 'Set up a PostgreSQL database alongside the Gitea instance. Default is true. If set to false the values for giteaPostgresqlServiceName, giteaPostgresqlDatabaseName, giteaPostgresqlUser and giteaPostgresqlPassword need to be specified to connect to an existing PostgreSQL database. If set to true no values need to be specified for database name, database service, database user and database service.'
                type: boolean
              postgresqlServiceName:
                description: Name of the PostgreSQL database service. Default is 'postgresql-' followed by the name of the Gitea resource.
                type: string
              postgresqlDatabaseName:
                description: Name of the PostgreSQL Database to be created. Default is 'giteadb'.
                type: string
              postgresqlUser:
                description: Username to be created in the PostgreSQL database. Default is 'giteauser'.
                type: string
              postgresqlPassword:
                description: Password to be used for the PostgreSQL database user. Default is 'giteapassword'.
                type: string
              postgresqlVolumeSize:
                description: Size of the persistent volume claim for the PostgreSQL database. Default
                  is '4Gi'.
                type: string
              postgresqlVolumeStorageClass:
                description: Storage Class to be used for the PostgreSQL persistent volume claim. Default is empty - which will create a PVC using the currently available default storage class on the cluster.
                type: string
              postgresqlImage:
                description: Container image for the PostgreSQL database. Default is 'registry.redhat.io/rhel8/postgresql-12'.
                type: string
              postgresqlImageTag:
                description: Image tag for the PostgreSQL container image. Default is 'latest'.
                type: string
              postgresqlMemoryRequest:
                description: Memory request for the PostgreSQL database. Default is '512Mi'.
                type: string
              postgresqlMemoryLimit:
                description: Memory limit for the PostgreSQL database. Default is '512Mi'.
                type: string
              postgresqlCpuRequest:
                description: CPU request for the PostgreSQL database. Default is '200m'.
                anyOf:
                - type: integer
                - type: string
                pattern: "^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$"
                x-kubernetes-int-or-string: true
              postgresqlCpuLimit:
                description: CPU limit for the PostgreSQL database. Default is '500m'.
                anyOf:
                - type: integer
                - type: string
                pattern: "^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$"
                x-kubernetes-int-or-string: true

              giteaServiceName:
                description: Name of the Gitea Service to be deployed. Defaults to the name of the Gitea custom resource.
                type: string
              giteaSsl:
                description: Create an HTTPS terminated route for Gitea. Default is 'false'
                type: boolean
              giteaRoute:
                description: Specify the whole Route URL for the Gitea Route. Default is ''. Make sure the route is reachable from outside the cluster.
                type: string
              giteaVolumeSize:
                description: Size of the persistent volume claim for Gitea. Default is '4Gi'.
                type: string
              giteaVolumeStorageClass:
                description: Storage Class to be used for the Gitea persistent volume claim. Default is empty - which will create a PVC using the currently available default storage class on the cluster.
                type: string
              giteaImage:
                description: Container image for Gitea. Default is 'quay.io/gpte-devops-automation/gitea'.
                type: string
              giteaImageTag:
                description: Image tag for the Gitea container image. Default is 'latest'.
                type: string
              giteaMemoryRequest:
                description: Memory request for Gitea. Default is '1Gi'.
                type: string
              giteaMemoryLimit:
                description: Memory limit for Gitea. Default is '1Gi'.
                type: string
              giteaCpuRequest:
                description: CPU request for Gitea. Default is '200m'.
                anyOf:
                - type: integer
                - type: string
                pattern: "^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$"
                x-kubernetes-int-or-string: true
              giteaCpuLimit:
                description: CPU limit for Gitea. Default is '500m'.
                anyOf:
                - type: integer
                - type: string
                pattern: "^(\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\\\+|-)?(([0-9]+(\\\\.[0-9]*)?)|(\\\\.[0-9]+))))?$"
                x-kubernetes-int-or-string: true

              giteaPostgresqlServiceName:
                description: 'Name of the PostgreSQL service. Only required when PostgreSQL is not set up by the operator. Default: postgresql- followed by the Gitea resource name.'
                type: string
              giteaPostgresqlDatabaseName:
                description: 'Name of the PostgreSQL database. Only required when PostgreSQL is not set up by the operator. Default: giteadb'
                type: string
              giteaPostgresqlUser:
                description: 'Name of the PostgreSQL user. Only required when PostgreSQL is not set up by the operator. Default: giteauser'
                type: string
              giteaPostgresqlPassword:
                description: 'PostgreSQL password. Only required when PostgreSQL is not set up by the operator. Default: giteapassword'
                type: string

              giteaAdminUser:
                description: 'User ID for the Admin User to be created. If not specified no admin user will be created. Note that if giteaDisableRegistration is set to false and no admin user will be created you will not be able to create any users for Gitea. Default: ""'
                type: string
              giteaAdminPassword:
                description: 'Password for the Gitea admin user. If not specified or empty a random password will be created with length of giteaAdminPasswordLength random ASCII characters. Default: ""'
                type: string
              giteaAdminPasswordLength:
                description: 'If a giteaAdminUser is provided but no giteaAdminPassword is provided a random ASCII password with the length specified will be created. Default: 16'
                type: integer
              giteaAdminEmail:
                description: 'e-mail address for the Gitea Admin User. Default: "notset@notset.org"'
                type: string

              giteaCreateUsers:
                description: 'Create users in Gitea. Only possible if an admin user is also being created. Default: false'
                type: boolean
              giteaUserNumber:
                description: 'Number of users to create in Gitea. If 1 then only one user will be created with the username from giteaGenerateUserFormat. If more than one then users will be created according to the format in giteaGenerateUserFormat. Default: 2'
                type: integer
              giteaGenerateUserFormat:
                description: 'Format for user names to be created. This will be taken literally if only one user is to be created (e.g. lab-user). If more than one user is to be created the format needs to include a "%d" to set the user number. Default: "user%d"'
                type: string
              giteaUserPassword:
                description: 'Password for all created Gitea users. If not specified or empty a random password will be created with length of giteaUserPasswordLength random ASCII characters. Default: ""'
                type: string
              giteaUserPasswordLength:
                description: 'If a giteaCreateUsers is set but no giteaUserPassowrd is provided a random ASCII password with the length specified will be created. Default: 16'
                type: integer
              giteaUserEmailDomain:
                description: 'e-mail domain for the created Gitea users. Default: "example.com"'
                type: string

              giteaMigrateRepositories:
                description: 'For created users migrate repositories from another location, e.g. GitHub. Default: false'
                type: boolean
              giteaRepositoriesList:
                description: 'List of repositories to be created. Each repository is an array of "repo: <source URL", "name: <name of migrated repository>" and "private: true | false". Default: []'
                type: array
                items:
                  type: object
                  properties:
                    repo:
                      description: 'Source repository URL to clone.'
                      type: string
                    name:
                      description: 'Name of the repository in Gitea.'
                      type: string
                    private:
                      description: 'Create private repository in Gitea.'
                      type: boolean

              giteaHttpPort:
                description: 'Port for Gitea to listen on. Default: 3000'
                type: integer
              giteaSshPort:
                description: 'Port for Gitea to start an SSH server on. Default: 2022'
                type: integer
              giteaDisableSsh:
                description: 'Disable SSH for Gitea. Default: true'
                type: boolean
              giteaStartSshServer:
                description: 'Start SSH Server in the Gitea container. Default: false'
                type: boolean
              giteaDisableRegistration:
                description: 'Disable user self-registration. If this flag is set an Admin User should be specified to be created. Otherwise no users can be created at all. Default: false'
                type: boolean
              giteaEnableCaptcha:
                description: 'Display Captcha when users are registering a new account. No effect if giteaDisableRegistration is set to false. Default: false'
                type: boolean
              giteaAllowCreateOrganization:
                description: 'Allow users to create organizations in Gitea. Default: true'
                type: boolean
              giteaAllowLocalNetworkMigration:
                description: 'Allow migration of repositories hosted on local network IPs as defined by RFC 1918, RFC 1122, RFC 4632 and RFC 4291. Default: false'
                type: boolean

              giteaMailerEnabled:
                description: 'Enable e-mail integration for Gitea. If set to true the other giteaMailer* properties need to be provided. See https://docs.gitea.io/en-us/email-setup/ for example values. Default: false'
                type: boolean
              giteaMailerFrom:
                description: 'E-mail integration. FROM e-mail address to be used. Default: ""'
                type: string
              giteaMailerType:
                description: 'Type of e-mail provider to be used. Default: smtp'
                type: string
              giteaMailerHost:
                description: 'Hostname of the e-mail server to be used. Default: ""'
                type: string
              giteaMailerTls:
                description: 'Use TLS encryption when connecting to the mailer host. Default: true'
                type: boolean
              giteaMailerUser:
                description: 'User ID on the e-mail server to use. Frequently the same as the value for giteaMailerFrom. Default: ""'
                type: string
              giteaMailerPassword:
                description: 'Password for the User ID on the e-mail server to be used. May need to be an app-specific password if two-factor authentication is enabled on the e-mail server. Default: ""'
                type: string
              giteaMailerHeloHostname:
                description: 'Helo Hostname for the e-mail server. Not required for all e-mail providers. Default: ""'
                type: string

              giteaRegisterEmailConfirm:
                description: 'Send e-mail confirmation to users when self-registering. Users must click a link to validate their e-mail address before the account gets created. Requires the mailer to be configured correctly. Default: false'
                type: boolean
              giteaEnableNotifyMail:
                description: 'Send e-mail notifications to users for various tasks in Gitea. Requires the mailer to be configured correctly. Default: false'
                type: boolean

              giteaEnvVars:
                description: 'Environment variables to be set in the Gitea container. Default: []'
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: 'Name of the environment variable to set on the Gitea container.'
                      type: string
                    value:
                      description: 'Value of the environment variable to set on the Gitea container.'
                      type: string
